title: Blog of neural-koala
description: Blog site of neural-koala.
theme: just-the-docs

url: https://neural-koala.github.io
heading_anchors: true
heading_numbering: true

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

just_the_docs:
  collections:
    docs:
      name: docs

aux_links:
  "GitHub":
    - "https://github.com/neural-koala"
  "RSS/Atom Feed":
    - "/feed/docs.xml"

collections:
  docs:
    output: true

feed:
  collections:
    docs:
      path: "/feed/docs.xml"

